import Image from "next/image";
import { WhatsappButton } from "@/components/WhatsappButton";

const products = [
  ["Brindes personalizados", "Canetas, chaveiros, squeezes, calendários e itens promocionais para divulgar sua marca com qualidade.", "btn-whatsapp-brindes", "brindes", "/images/produtos/materiais-promocionais.jpg"],
  ["Camisetas e uniformes personalizados", "Camisetas promocionais, uniformes para empresas, eventos, equipes e campanhas especiais.", "btn-whatsapp-camisetas", "camisetas", "/images/produtos/camisetas.jpg"],
  ["Kits corporativos personalizados", "Combinações de brindes para clientes, colaboradores, eventos, ações comerciais e campanhas internas.", "btn-whatsapp-kits", "kits", "/images/produtos/kits-corporativos.jpg"],
  ["Sacochilas e materiais para eventos", "Produtos personalizados para corridas, feiras, escolas, empresas e eventos corporativos.", "btn-whatsapp-sacochilas", "sacochilas", "/images/produtos/sacochilas.jpg"],
  ["Canetas personalizadas", "Opções práticas e acessíveis para divulgar sua empresa no dia a dia dos seus clientes.", "btn-whatsapp-canetas", "canetas", "/images/produtos/canetas.jpg"],
  ["Chaveiros personalizados", "Brindes úteis, duráveis e ideais para empresas, imobiliárias, concessionárias, eventos e campanhas.", "btn-whatsapp-chaveiros", "chaveiros", "/images/produtos/chaveiros.jpg"],
] as const;

export default function Home() {
  return <main>
    <header className="fixed inset-x-0 top-0 z-50 border-b bg-white/95 backdrop-blur"><div className="container-section flex h-20 items-center justify-between"><a href="#top" className="flex items-center gap-3"><Image src="/images/logo-mr-mega-marca.png" alt="MR e Mega Marca" width={180} height={54} className="h-12 w-auto"/></a><nav className="hidden gap-6 md:flex">{["produtos","como-funciona","tradicao","faq","contato"].map(i=><a key={i} href={`#${i}`} className="text-sm font-medium text-slate-700 hover:text-brandBlue">{i.replace("-"," ")}</a>)}</nav><WhatsappButton id="btn-whatsapp-header" category="geral" label="Solicitar orçamento"/></div></header>
    <section id="top" className="bg-gradient-to-br from-brandBlue via-slate-950 to-brandRed pt-32 text-white"><div className="container-section grid gap-10 py-16 lg:grid-cols-2 lg:items-center"><div><h1 className="text-4xl font-black leading-tight sm:text-5xl">Brindes personalizados para empresas, eventos e ações promocionais</h1><p className="mt-5 text-lg text-slate-200">Canetas, chaveiros, squeezes, sacochilas, camisetas, kits corporativos e muito mais, com atendimento rápido pelo WhatsApp e a tradição de quem atua há mais de 40 anos no mercado.</p><div className="mt-6 flex flex-wrap gap-2">{["40+ anos de tradição","Orçamento gratuito","Atendimento rápido","Todo o Brasil, conforme viabilidade"].map(s=><span key={s} className="rounded-full bg-white/15 px-4 py-2 text-sm">{s}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><WhatsappButton id="btn-whatsapp-hero" category="geral" label="Solicitar orçamento no WhatsApp"/><a href="#produtos" className="inline-flex rounded-xl border border-white/50 px-6 py-3 font-semibold">Ver produtos em destaque</a></div></div><div className="rounded-2xl bg-white/10 p-4"><Image src="/images/produtos/kits-corporativos.jpg" alt="Produtos personalizados" width={1200} height={900} className="rounded-xl"/></div></div></section>
    <section id="produtos" className="container-section py-20"><h2 className="section-title">Escolha o produto ideal para personalizar sua marca</h2><p className="section-subtitle">Soluções personalizadas para empresas, eventos, equipes, campanhas promocionais e ações corporativas.</p><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{products.map(([title,desc,id,cat,img])=><article key={id} className="rounded-2xl border p-4 shadow-soft"><Image src={img} alt={title} width={1200} height={900} className="rounded-lg"/><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 text-slate-600">{desc}</p><div className="mt-5"><WhatsappButton id={id} category={cat} label={`Orçar ${title.toLowerCase()}`} product={title}/></div></article>)}</div></section>
    <section id="como-funciona" className="bg-slate-100 py-20"><div className="container-section"><h2 className="section-title">Como solicitar seu orçamento</h2><p className="section-subtitle">Em poucos passos, nossa equipe entende sua necessidade e indica as melhores opções para o seu projeto.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{["Escolha o produto","Informe a quantidade","Envie sua logo ou ideia","Receba atendimento personalizado"].map((s,i)=><div key={s} className="rounded-xl bg-white p-5"><p className="text-sm font-bold text-brandRed">Passo {i+1}</p><h3 className="text-lg font-bold">{s}</h3></div>)}</div><div className="mt-8"><WhatsappButton id="btn-whatsapp-como-funciona" category="geral" label="Começar orçamento agora"/></div></div></section>
    <section id="tradicao" className="container-section py-20"><h2 className="section-title">Mais de 40 anos ajudando empresas a divulgarem suas marcas</h2><p className="section-subtitle">A MR & Mega Marca possui mais de 40 anos de tradição no mercado de produtos personalizados...</p></section>
    <section className="bg-slate-900 py-16 text-white"><div className="container-section text-center"><h2 className="text-3xl font-extrabold">Quer personalizar produtos para sua empresa ou evento?</h2><p className="mx-auto mt-4 max-w-3xl text-slate-300">Solicite um orçamento gratuito pelo WhatsApp e receba uma orientação personalizada.</p><div className="mt-8"><WhatsappButton id="btn-whatsapp-cta-intermediario" category="geral" label="Falar com a Mega Marca no WhatsApp"/></div></div></section>
    <section id="faq" className="container-section py-20"><h2 className="section-title">Perguntas frequentes</h2><div className="mt-8 space-y-3">{[["O orçamento é gratuito?","Sim. Você pode solicitar seu orçamento gratuitamente pelo WhatsApp..."],["Existe pedido mínimo?","Sim. O pedido mínimo pode variar conforme o tipo de produto..."],["Preciso ter a arte pronta?","Não necessariamente. Caso você já tenha logo, arte ou referência..."],["Vocês atendem quais regiões?","Atendemos todo o Brasil, conforme viabilidade do pedido..."],["Quais produtos posso personalizar?","Você pode solicitar orçamento para brindes personalizados..."],["Em quanto tempo recebo retorno?","O atendimento é feito pelo WhatsApp..."]].map(([q,a])=><details key={q} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-2 text-slate-600">{a}</p></details>)}</div></section>
    <section id="contato" className="bg-brandBlue py-16 text-white"><div className="container-section text-center"><h2 className="text-3xl font-extrabold">Divulgue sua marca com produtos personalizados de qualidade</h2><p className="mx-auto mt-4 max-w-3xl text-slate-100">Conte com a experiência de uma empresa com mais de 40 anos de tradição.</p><div className="mt-8"><WhatsappButton id="btn-whatsapp-final" category="geral" label="Solicitar orçamento no WhatsApp"/></div></div></section>
    <footer className="bg-brandDark py-12 text-slate-300"><div className="container-section grid gap-8 md:grid-cols-2"><div><Image src="/images/logo-mr-mega-marca.png" alt="Logo MR e Mega Marca" width={180} height={54} className="h-12 w-auto"/><p className="mt-4">Brindes, camisetas, uniformes e materiais personalizados para empresas, eventos e ações promocionais.</p></div><div><p>WhatsApp: 35 3743 1554</p><p>www.mrmegamarca.com.br</p></div></div></footer>
    <div className="fixed bottom-5 right-5 z-50"><WhatsappButton id="btn-whatsapp-flutuante" category="geral" label="WhatsApp" className="rounded-full px-5"/></div>
  </main>;
}
